### YamlMime:ManagedReference
items:
- uid: System.Runtime.Remoting.RemotingTimeoutException
  id: RemotingTimeoutException
  children:
  - System.Runtime.Remoting.RemotingTimeoutException.#ctor
  - System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String)
  - System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: RemotingTimeoutException
  nameWithType: RemotingTimeoutException
  fullName: System.Runtime.Remoting.RemotingTimeoutException
  type: Class
  summary: "Undantag som utlöses när servern eller klienten inte kan nås för en tidigare angiven tidsperiod."
  remarks: "RemotingTimeoutException genereras när ett fjärranrop inte slutförs inom den angivna timeout-tiden.       RemotingTimeoutException använder HRESULT COR_E_REMOTING, som har värdet 0x8013150B.       RemotingTimeoutException använder förvalet <xref:System.Object.Equals%2A>-implementering som stöder referenslikheten.</xref:System.Object.Equals%2A>       En lista med inledande egenskapsvärden för en instans av RemotingTimeoutException finns RemotingTimeoutException konstruktorer."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public class RemotingTimeoutException : System.Runtime.Remoting.RemotingException
  inheritance:
  - System.Exception
  - System.SystemException
  - System.Runtime.Remoting.RemotingException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor
  id: '#ctor'
  parent: System.Runtime.Remoting.RemotingTimeoutException
  langs:
  - csharp
  name: RemotingTimeoutException()
  nameWithType: RemotingTimeoutException.RemotingTimeoutException()
  fullName: System.Runtime.Remoting.RemotingTimeoutException.RemotingTimeoutException()
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Runtime.Remoting
  summary: "Initierar en ny instans av den <xref href=&quot;System.Runtime.Remoting.RemotingTimeoutException&quot;> </xref> klass med standardegenskaper."
  remarks: "<xref:System.Runtime.Remoting.RemotingTimeoutException>ärver från en <xref:System.Exception>klass.</xref:System.Exception></xref:System.Runtime.Remoting.RemotingTimeoutException> I följande tabell visas första egenskapsvärden för en instans av klassen <xref:System.Runtime.Remoting.RemotingTimeoutException>: | Egenskapen | Värdet |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`|   | <xref:System.Exception.Message%2A>| Lokaliserade felmeddelandet <xref:System.Runtime.Remoting.RemotingTimeoutException>|</xref:System.Runtime.Remoting.RemotingTimeoutException> </xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> </xref:System.Runtime.Remoting.RemotingTimeoutException>"
  syntax:
    content: public RemotingTimeoutException ();
    parameters: []
  overload: System.Runtime.Remoting.RemotingTimeoutException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Runtime.Remoting.RemotingTimeoutException
  langs:
  - csharp
  name: RemotingTimeoutException(String)
  nameWithType: RemotingTimeoutException.RemotingTimeoutException(String)
  fullName: System.Runtime.Remoting.RemotingTimeoutException.RemotingTimeoutException(String)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Runtime.Remoting
  summary: "Initierar en ny instans av <xref href=&quot;System.Runtime.Remoting.RemotingTimeoutException&quot;> </xref> klass med ett angivet meddelande."
  remarks: "<xref:System.Runtime.Remoting.RemotingTimeoutException>ärver från en <xref:System.Exception>klass.</xref:System.Exception></xref:System.Runtime.Remoting.RemotingTimeoutException> I följande tabell visas första egenskapsvärden för en instans av klassen <xref:System.Runtime.Remoting.RemotingTimeoutException>: | Egenskapstypen | Villkoret |   |-------------------|---------------|   | <xref:System.Exception.InnerException%2A>| `null`|   | <xref:System.Exception.Message%2A>| Den `message` strängen |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> </xref:System.Runtime.Remoting.RemotingTimeoutException>"
  syntax:
    content: public RemotingTimeoutException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Det meddelande som indikerar orsaken till varför undantaget inträffade."
  overload: System.Runtime.Remoting.RemotingTimeoutException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Runtime.Remoting.RemotingTimeoutException
  langs:
  - csharp
  name: RemotingTimeoutException(String,Exception)
  nameWithType: RemotingTimeoutException.RemotingTimeoutException(String,Exception)
  fullName: System.Runtime.Remoting.RemotingTimeoutException.RemotingTimeoutException(String,Exception)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Runtime.Remoting
  summary: "Initierar en ny instans av den <xref href=&quot;System.Runtime.Remoting.RemotingTimeoutException&quot;> </xref> klass med ett angivet meddelande och en referens till det interna undantaget som är orsaken till det här undantaget."
  remarks: "Ett undantag som utlöses när ett direkt resultat av ett tidigare undantag måste innehålla en referens till det tidigare undantaget i den <xref:System.Exception.InnerException%2A>egenskapen.</xref:System.Exception.InnerException%2A> Den <xref:System.Exception.InnerException%2A>-egenskap returnerar samma värde som överförs till konstruktorn eller `null` om den <xref:System.Exception.InnerException%2A>egenskapen tillhandahåller inte värdet i det interna undantaget för konstruktorn.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       I följande tabell visas första egenskapsvärden för en instans av klassen <xref:System.Runtime.Remoting.RemotingTimeoutException>: | Egenskapen | Värdet |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| I det interna undantaget referens |   | <xref:System.Exception.Message%2A>| Meddelandet felsträng |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> </xref:System.Runtime.Remoting.RemotingTimeoutException>"
  syntax:
    content: public RemotingTimeoutException (string message, Exception InnerException);
    parameters:
    - id: message
      type: System.String
      description: "Felmeddelandet som förklarar orsaken till undantaget."
    - id: InnerException
      type: System.Exception
      description: "Undantag som är orsaken till det aktuella undantaget. Om den `InnerException` parametern är inte <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>, det aktuella undantaget utlöses i en <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> block som hanterar det interna undantaget."
  overload: System.Runtime.Remoting.RemotingTimeoutException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Runtime.Remoting.RemotingException
  isExternal: false
  name: System.Runtime.Remoting.RemotingException
- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor
  parent: System.Runtime.Remoting.RemotingTimeoutException
  isExternal: false
  name: RemotingTimeoutException()
  nameWithType: RemotingTimeoutException.RemotingTimeoutException()
  fullName: System.Runtime.Remoting.RemotingTimeoutException.RemotingTimeoutException()
- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String)
  parent: System.Runtime.Remoting.RemotingTimeoutException
  isExternal: false
  name: RemotingTimeoutException(String)
  nameWithType: RemotingTimeoutException.RemotingTimeoutException(String)
  fullName: System.Runtime.Remoting.RemotingTimeoutException.RemotingTimeoutException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String,System.Exception)
  parent: System.Runtime.Remoting.RemotingTimeoutException
  isExternal: false
  name: RemotingTimeoutException(String,Exception)
  nameWithType: RemotingTimeoutException.RemotingTimeoutException(String,Exception)
  fullName: System.Runtime.Remoting.RemotingTimeoutException.RemotingTimeoutException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor*
  parent: System.Runtime.Remoting.RemotingTimeoutException
  isExternal: false
  name: RemotingTimeoutException
  nameWithType: RemotingTimeoutException.RemotingTimeoutException
