### YamlMime:ManagedReference
items:
- uid: System.Windows.Forms.DataGridViewDataErrorEventArgs
  id: DataGridViewDataErrorEventArgs
  children:
  - System.Windows.Forms.DataGridViewDataErrorEventArgs.#ctor(System.Exception,System.Int32,System.Int32,System.Windows.Forms.DataGridViewDataErrorContexts)
  - System.Windows.Forms.DataGridViewDataErrorEventArgs.Context
  - System.Windows.Forms.DataGridViewDataErrorEventArgs.Exception
  - System.Windows.Forms.DataGridViewDataErrorEventArgs.ThrowException
  langs:
  - csharp
  name: DataGridViewDataErrorEventArgs
  nameWithType: DataGridViewDataErrorEventArgs
  fullName: System.Windows.Forms.DataGridViewDataErrorEventArgs
  type: Class
  summary: "Tillhandahåller data för den <xref href=&quot;System.Windows.Forms.DataGridView.DataError&quot;> </xref> händelse."
  remarks: "Hantering av <xref:System.Windows.Forms.DataGridView.DataError>händelsen kan du hantera undantag från kod utanför din kontroll (t.ex, genom en extern datakälla).</xref:System.Windows.Forms.DataGridView.DataError> Använd den <xref:System.Windows.Forms.DataGridViewDataErrorEventArgs.Context%2A>egenskapen för att avgöra tillståndet för den <xref:System.Windows.Forms.DataGridView>vid tidpunkten för undantaget.</xref:System.Windows.Forms.DataGridView> </xref:System.Windows.Forms.DataGridViewDataErrorEventArgs.Context%2A> Använd den <xref:System.Windows.Forms.DataGridViewDataErrorEventArgs.Exception%2A>egenskapen att hämta Undantagsdata.</xref:System.Windows.Forms.DataGridViewDataErrorEventArgs.Exception%2A> Om du vill hantera undantag av ytterligare händelsehanterare den <xref:System.Windows.Forms.DataGridViewDataErrorEventArgs.ThrowException%2A>egenskapen `true`.</xref:System.Windows.Forms.DataGridViewDataErrorEventArgs.ThrowException%2A>       Den <xref:System.Windows.Forms.DataGridViewCellCancelEventArgs.ColumnIndex%2A>och <xref:System.Windows.Forms.DataGridViewCellCancelEventArgs.RowIndex%2A>egenskaperna normalt visar cellen där datafel uppstod.</xref:System.Windows.Forms.DataGridViewCellCancelEventArgs.RowIndex%2A> </xref:System.Windows.Forms.DataGridViewCellCancelEventArgs.ColumnIndex%2A> När fel uppstår i en extern datakälla, men tillhandahålla datakällan inte kolumnen där felet inträffade. I det här fallet den <xref:System.Windows.Forms.DataGridViewCellCancelEventArgs.ColumnIndex%2A>egenskapen tyder vanligtvis på kolumnen i den aktiva cellen vid tidpunkten för felet.</xref:System.Windows.Forms.DataGridViewCellCancelEventArgs.ColumnIndex%2A>"
  example:
  - "The following code example demonstrates how to respond to information provided by the DataGridViewDataErrorEventArgs class. This example is part of a larger example available in the <xref:System.Windows.Forms.DataGridViewComboBoxColumn> class overview topic.  \n  \n [!code-cpp[System.Windows.Forms.DataGridViewColumn_AllColumns_Bound_Employees#50](~/add/codesnippet/cpp/t-system.windows.forms.d_56_1.cpp)]\n [!code-cs[System.Windows.Forms.DataGridViewColumn_AllColumns_Bound_Employees#50](~/add/codesnippet/csharp/t-system.windows.forms.d_56_1.cs)]\n [!code-vb[System.Windows.Forms.DataGridViewColumn_AllColumns_Bound_Employees#50](~/add/codesnippet/visualbasic/t-system.windows.forms.d_56_1.vb)]"
  syntax:
    content: 'public class DataGridViewDataErrorEventArgs : System.Windows.Forms.DataGridViewCellCancelEventArgs'
  inheritance:
  - System.ComponentModel.CancelEventArgs
  - System.Windows.Forms.DataGridViewCellCancelEventArgs
  implements: []
  inheritedMembers:
  - System.Windows.Forms.DataGridViewCellCancelEventArgs.ColumnIndex
  - System.Windows.Forms.DataGridViewCellCancelEventArgs.RowIndex
  platform:
  - net462
- uid: System.Windows.Forms.DataGridViewDataErrorEventArgs.#ctor(System.Exception,System.Int32,System.Int32,System.Windows.Forms.DataGridViewDataErrorContexts)
  id: '#ctor(System.Exception,System.Int32,System.Int32,System.Windows.Forms.DataGridViewDataErrorContexts)'
  parent: System.Windows.Forms.DataGridViewDataErrorEventArgs
  langs:
  - csharp
  name: DataGridViewDataErrorEventArgs(Exception,Int32,Int32,DataGridViewDataErrorContexts)
  nameWithType: DataGridViewDataErrorEventArgs.DataGridViewDataErrorEventArgs(Exception,Int32,Int32,DataGridViewDataErrorContexts)
  fullName: System.Windows.Forms.DataGridViewDataErrorEventArgs.DataGridViewDataErrorEventArgs(Exception,Int32,Int32,DataGridViewDataErrorContexts)
  type: Constructor
  assemblies:
  - System.Windows.Forms
  namespace: System.Windows.Forms
  summary: "Initierar en ny instans av den <xref href=&quot;System.Windows.Forms.DataGridViewDataErrorEventArgs&quot;> </xref> klass."
  syntax:
    content: public DataGridViewDataErrorEventArgs (Exception exception, int columnIndex, int rowIndex, System.Windows.Forms.DataGridViewDataErrorContexts context);
    parameters:
    - id: exception
      type: System.Exception
      description: "Undantag som uppstått."
    - id: columnIndex
      type: System.Int32
      description: "Kolumnindex för cellen som aktiveras av <xref href=&quot;System.Windows.Forms.DataGridView.DataError&quot;> </xref>."
    - id: rowIndex
      type: System.Int32
      description: "Radindex för cellen som aktiveras av <xref href=&quot;System.Windows.Forms.DataGridView.DataError&quot;> </xref>."
    - id: context
      type: System.Windows.Forms.DataGridViewDataErrorContexts
      description: "En binär kombination av <xref href=&quot;System.Windows.Forms.DataGridViewDataErrorContexts&quot;> </xref> värden som anger den kontext där felet inträffade."
  overload: System.Windows.Forms.DataGridViewDataErrorEventArgs.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Forms.DataGridViewDataErrorEventArgs.Context
  id: Context
  parent: System.Windows.Forms.DataGridViewDataErrorEventArgs
  langs:
  - csharp
  name: Context
  nameWithType: DataGridViewDataErrorEventArgs.Context
  fullName: System.Windows.Forms.DataGridViewDataErrorEventArgs.Context
  type: Property
  assemblies:
  - System.Windows.Forms
  namespace: System.Windows.Forms
  summary: "Hämtar information om tillståndet för den <xref href=&quot;System.Windows.Forms.DataGridView&quot;> </xref> när felet inträffade."
  remarks: "Medlemmar i den <xref:System.Windows.Forms.DataGridViewDataErrorContexts>uppräkningen kan kombineras med de bitvis `OR` operatorn för att representera tillståndet för en databunden <xref:System.Windows.Forms.DataGridView>när ett fel uppstod.</xref:System.Windows.Forms.DataGridView> </xref:System.Windows.Forms.DataGridViewDataErrorContexts> Till exempel om en användare anger ett ogiltigt cellvärde (t.ex att ange ett namn i en cell som kräver ett datum) och väljer sedan en annan cell i <xref:System.Windows.Forms.DataGridView>försöker genomföra ogiltig cellvärdet.</xref:System.Windows.Forms.DataGridView> När överföringen misslyckas, som <xref:System.Windows.Forms.DataGridView>höjer en <xref:System.Windows.Forms.DataGridView.DataError>händelse vars Context-egenskap har värdet <xref:System.Windows.Forms.DataGridViewDataErrorContexts>och <xref:System.Windows.Forms.DataGridViewDataErrorContexts>.</xref:System.Windows.Forms.DataGridViewDataErrorContexts> </xref:System.Windows.Forms.DataGridViewDataErrorContexts> </xref:System.Windows.Forms.DataGridView.DataError> </xref:System.Windows.Forms.DataGridView>"
  example:
  - "The following code example demonstrates how to investigate the error context. This example is part of a larger example available in the <xref:System.Windows.Forms.DataGridViewComboBoxColumn> class overview topic.  \n  \n [!code-cpp[System.Windows.Forms.DataGridViewColumn_AllColumns_Bound_Employees#50](~/add/codesnippet/cpp/p-system.windows.forms.d_134_1.cpp)]\n [!code-cs[System.Windows.Forms.DataGridViewColumn_AllColumns_Bound_Employees#50](~/add/codesnippet/csharp/p-system.windows.forms.d_134_1.cs)]\n [!code-vb[System.Windows.Forms.DataGridViewColumn_AllColumns_Bound_Employees#50](~/add/codesnippet/visualbasic/p-system.windows.forms.d_134_1.vb)]"
  syntax:
    content: public System.Windows.Forms.DataGridViewDataErrorContexts Context { get; }
    return:
      type: System.Windows.Forms.DataGridViewDataErrorContexts
      description: "En binär kombination av den <xref href=&quot;System.Windows.Forms.DataGridViewDataErrorContexts&quot;> </xref> värden som anger kontext där felet inträffade."
  overload: System.Windows.Forms.DataGridViewDataErrorEventArgs.Context*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Forms.DataGridViewDataErrorEventArgs.Exception
  id: Exception
  parent: System.Windows.Forms.DataGridViewDataErrorEventArgs
  langs:
  - csharp
  name: Exception
  nameWithType: DataGridViewDataErrorEventArgs.Exception
  fullName: System.Windows.Forms.DataGridViewDataErrorEventArgs.Exception
  type: Property
  assemblies:
  - System.Windows.Forms
  namespace: System.Windows.Forms
  summary: "Hämtar det undantag som representerar felet."
  remarks: "Att hantera undantaget av fler än ett <xref:System.Windows.Forms.DataGridViewDataErrorEventHandler>, utlöser undantag igen i slutet av en hanterare genom att ange den <xref:System.Windows.Forms.DataGridViewDataErrorEventArgs.ThrowException%2A>egenskapen `true`.</xref:System.Windows.Forms.DataGridViewDataErrorEventArgs.ThrowException%2A> </xref:System.Windows.Forms.DataGridViewDataErrorEventHandler>"
  example:
  - "The following code example demonstrates checking the Exception property. This example is part of a larger example available in the <xref:System.Windows.Forms.DataGridViewComboBoxColumn> class overview topic.  \n  \n [!code-cpp[System.Windows.Forms.DataGridViewColumn_AllColumns_Bound_Employees#50](~/add/codesnippet/cpp/p-system.windows.forms.d_249_1.cpp)]\n [!code-cs[System.Windows.Forms.DataGridViewColumn_AllColumns_Bound_Employees#50](~/add/codesnippet/csharp/p-system.windows.forms.d_249_1.cs)]\n [!code-vb[System.Windows.Forms.DataGridViewColumn_AllColumns_Bound_Employees#50](~/add/codesnippet/visualbasic/p-system.windows.forms.d_249_1.vb)]"
  syntax:
    content: public Exception Exception { get; }
    return:
      type: System.Exception
      description: "En <xref:System.Exception>som representerar felet.</xref:System.Exception>"
  overload: System.Windows.Forms.DataGridViewDataErrorEventArgs.Exception*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Forms.DataGridViewDataErrorEventArgs.ThrowException
  id: ThrowException
  parent: System.Windows.Forms.DataGridViewDataErrorEventArgs
  langs:
  - csharp
  name: ThrowException
  nameWithType: DataGridViewDataErrorEventArgs.ThrowException
  fullName: System.Windows.Forms.DataGridViewDataErrorEventArgs.ThrowException
  type: Property
  assemblies:
  - System.Windows.Forms
  namespace: System.Windows.Forms
  summary: "Hämtar eller anger ett värde som anger om du vill utlösa undantag efter den <xref href=&quot;System.Windows.Forms.DataGridViewDataErrorEventHandler&quot;> </xref> ombud är klar."
  remarks: "Den här egenskapen `false` om den <xref:System.Windows.Forms.DataGridViewDataErrorEventHandler>har behandlas undantag som representeras av den <xref:System.Windows.Forms.DataGridViewDataErrorEventArgs.Exception%2A>egenskapen, och du inte vill att sprida undantag till en annan <xref:System.Windows.Forms.DataGridViewDataErrorEventHandler>som kan hantera den <xref:System.Windows.Forms.DataGridView.DataError>händelse.</xref:System.Windows.Forms.DataGridView.DataError> </xref:System.Windows.Forms.DataGridViewDataErrorEventHandler> </xref:System.Windows.Forms.DataGridViewDataErrorEventArgs.Exception%2A> </xref:System.Windows.Forms.DataGridViewDataErrorEventHandler>       För felsökning, kan det vara praktiskt att sprida undantaget och inspektera stack-spårning för information om kontexten för felet."
  example:
  - "The following code example demonstrates using the ThrowException property to indicate that the exception should not be thrown. This example is part of a larger example available in the <xref:System.Windows.Forms.DataGridViewComboBoxColumn> class overview topic.  \n  \n [!code-cpp[System.Windows.Forms.DataGridViewColumn_AllColumns_Bound_Employees#50](~/add/codesnippet/cpp/p-system.windows.forms.d_202_1.cpp)]\n [!code-cs[System.Windows.Forms.DataGridViewColumn_AllColumns_Bound_Employees#50](~/add/codesnippet/csharp/p-system.windows.forms.d_202_1.cs)]\n [!code-vb[System.Windows.Forms.DataGridViewColumn_AllColumns_Bound_Employees#50](~/add/codesnippet/visualbasic/p-system.windows.forms.d_202_1.vb)]"
  syntax:
    content: public bool ThrowException { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Om den ska vara undantagsfel; Annars <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Standardvärdet är <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Windows.Forms.DataGridViewDataErrorEventArgs.ThrowException*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "När du anger egenskapen till <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>, <xref:System.Windows.Forms.DataGridViewDataErrorEventArgs.Exception*>egenskapsvärdet är <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>.</xref:System.Windows.Forms.DataGridViewDataErrorEventArgs.Exception*>"
  platform:
  - net462
references:
- uid: System.Windows.Forms.DataGridViewCellCancelEventArgs
  isExternal: false
  name: System.Windows.Forms.DataGridViewCellCancelEventArgs
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.Windows.Forms.DataGridViewDataErrorEventArgs.#ctor(System.Exception,System.Int32,System.Int32,System.Windows.Forms.DataGridViewDataErrorContexts)
  parent: System.Windows.Forms.DataGridViewDataErrorEventArgs
  isExternal: false
  name: DataGridViewDataErrorEventArgs(Exception,Int32,Int32,DataGridViewDataErrorContexts)
  nameWithType: DataGridViewDataErrorEventArgs.DataGridViewDataErrorEventArgs(Exception,Int32,Int32,DataGridViewDataErrorContexts)
  fullName: System.Windows.Forms.DataGridViewDataErrorEventArgs.DataGridViewDataErrorEventArgs(Exception,Int32,Int32,DataGridViewDataErrorContexts)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Windows.Forms.DataGridViewDataErrorContexts
  parent: System.Windows.Forms
  isExternal: false
  name: DataGridViewDataErrorContexts
  nameWithType: DataGridViewDataErrorContexts
  fullName: System.Windows.Forms.DataGridViewDataErrorContexts
- uid: System.Windows.Forms.DataGridViewDataErrorEventArgs.Context
  parent: System.Windows.Forms.DataGridViewDataErrorEventArgs
  isExternal: false
  name: Context
  nameWithType: DataGridViewDataErrorEventArgs.Context
  fullName: System.Windows.Forms.DataGridViewDataErrorEventArgs.Context
- uid: System.Windows.Forms.DataGridViewDataErrorEventArgs.Exception
  parent: System.Windows.Forms.DataGridViewDataErrorEventArgs
  isExternal: false
  name: Exception
  nameWithType: DataGridViewDataErrorEventArgs.Exception
  fullName: System.Windows.Forms.DataGridViewDataErrorEventArgs.Exception
- uid: System.Windows.Forms.DataGridViewDataErrorEventArgs.ThrowException
  parent: System.Windows.Forms.DataGridViewDataErrorEventArgs
  isExternal: false
  name: ThrowException
  nameWithType: DataGridViewDataErrorEventArgs.ThrowException
  fullName: System.Windows.Forms.DataGridViewDataErrorEventArgs.ThrowException
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Windows.Forms.DataGridViewDataErrorEventArgs.#ctor*
  parent: System.Windows.Forms.DataGridViewDataErrorEventArgs
  isExternal: false
  name: DataGridViewDataErrorEventArgs
  nameWithType: DataGridViewDataErrorEventArgs.DataGridViewDataErrorEventArgs
- uid: System.Windows.Forms.DataGridViewDataErrorEventArgs.Context*
  parent: System.Windows.Forms.DataGridViewDataErrorEventArgs
  isExternal: false
  name: Context
  nameWithType: DataGridViewDataErrorEventArgs.Context
- uid: System.Windows.Forms.DataGridViewDataErrorEventArgs.Exception*
  parent: System.Windows.Forms.DataGridViewDataErrorEventArgs
  isExternal: false
  name: Exception
  nameWithType: DataGridViewDataErrorEventArgs.Exception
- uid: System.Windows.Forms.DataGridViewDataErrorEventArgs.ThrowException*
  parent: System.Windows.Forms.DataGridViewDataErrorEventArgs
  isExternal: false
  name: ThrowException
  nameWithType: DataGridViewDataErrorEventArgs.ThrowException
